#!/usr/bin/env bash
#
# Hermes Agent 一键配置脚本
# 从 maozp2014/hermes-agent-memory full-upload 分支完整重建环境
#
# 用法：
#   bash hermes-setup.sh [HERMES_HOME]
#
# HERMES_HOME: 可选，目标目录，默认 ~/.hermes
#
set -euo pipefail

# ─────────────────────────────────────────────
# 1. 变量定义
# ─────────────────────────────────────────────
HERMES_HOME="${1:-$HOME/.hermes}"
AGENT_REPO="https://github.com/maozp2014/hermes-agent-memory.git"
BRANCH="full-upload"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TIMESTAMP="$(date '+%Y%m%d_%H%M%S')"

# 颜色输出
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ OK ]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ ERR]${NC}  $*" >&2; }

# ─────────────────────────────────────────────
# 2. 前置检查
# ─────────────────────────────────────────────
info "检查前置依赖..."
command -v git >/dev/null 2>&1 || { err "需要 git，请先安装"; exit 1; }
command -v python3 >/dev/null 2>&1 || { err "需要 python3，请先安装"; exit 1; }

PY_VERSION=$(python3 -c 'import sys; v=sys.version_info; print(f"{v.major}.{v.minor}")')
if [[ "$(echo -e "3.11\n$PY_VERSION" | sort -V | head -1)" != "3.11" ]]; then
    warn "Python 版本 $PY_VERSION < 3.11，部分功能可能不稳定"
fi

# ─────────────────────────────────────────────
# 3. 确认关键环境变量（交互式输入）
# ─────────────────────────────────────────────
info "──────────────────────────────"
info "  环境变量配置（必填）"
info "──────────────────────────────"

# MiniMax CN
if [[ -z "${MINIMAX_CN_API_KEY:-}" ]]; then
    echo -n "MiniMax CN API Key (sk-cp-...): "; read -rs MINIMAX_CN_API_KEY
    echo
fi
if [[ -z "${MINIMAX_CN_GROUP_ID:-}" ]]; then
    echo -n "MiniMax CN Group ID (数字): "; read -r MINIMAX_CN_GROUP_ID
fi

# GitHub Token
if [[ -z "${GITHUB_TOKEN:-}" ]]; then
    echo -n "GitHub Personal Access Token (ghp_...): "; read -rs GITHUB_TOKEN
    echo
fi

# 飞书（可选）
if [[ -z "${FEISHU_APP_ID:-}" ]]; then
    echo -n "飞书 App ID (cli_..., 可留空): "; read -r FEISHU_APP_ID
fi
if [[ -n "${FEISHU_APP_ID:-}" && -z "${FEISHU_APP_SECRET:-}" ]]; then
    echo -n "飞书 App Secret (可留空): "; read -rs FEISHU_APP_SECRET
    echo
fi

# ─────────────────────────────────────────────
# 4. 创建目录结构
# ─────────────────────────────────────────────
info "创建目录结构..."
mkdir -p "$HERMES_HOME"/{bin,cache,logs,sessions,skills,memories,cron/output,scripts,auth}

# 创建 hermes-agent 代码目录
AGENT_DIR="$HERMES_HOME/hermes-agent"
mkdir -p "$AGENT_DIR"

# ─────────────────────────────────────────────
# 5. 克隆 / 更新 hermes-agent 代码
# ─────────────────────────────────────────────
if [[ -d "$AGENT_DIR/.git" ]]; then
    info "更新 hermes-agent 代码 (pull)..."
    cd "$AGENT_DIR"
    # 注意：git push 协议被阻断，pull 理论上可行
    if git config remote.pushurl >/dev/null 2>&1 | grep -q "ghp_"; then
        warn "检测到 .git/config 包含真实 token，正在清除..."
        git remote set-url backup "https://github.com/maozp2014/hermes-agent-memory.git"
    fi
    if git remote -v 2>/dev/null | grep -q "origin"; then
        git fetch origin "$BRANCH" 2>/dev/null || warn "fetch origin 失败，继续使用本地版本"
    fi
else
    info "克隆 hermes-agent 仓库 (分支: $BRANCH)..."
    git clone --branch "$BRANCH" --depth=1 "$AGENT_REPO" "$AGENT_DIR"
fi

# ─────────────────────────────────────────────
# 6. 创建虚拟环境 & 安装依赖
# ─────────────────────────────────────────────
info "创建 Python 虚拟环境..."
VENV_DIR="$AGENT_DIR/venv"
if [[ ! -d "$VENV_DIR" ]]; then
    python3 -m venv "$VENV_DIR"
fi
source "$VENV_DIR/bin/activate"

info "安装 hermes-agent 依赖..."
pip install --quiet --upgrade pip wheel setuptools
pip install --quiet -e "$AGENT_DIR" 2>/dev/null || \
pip install --quiet -r "$AGENT_DIR/requirements.txt"

# 确保关键依赖
pip install --quiet pyyaml requests rich prompt-toolkit

# ─────────────────────────────────────────────
# 7. 生成 .env 文件
# ─────────────────────────────────────────────
info "生成 ~/.hermes/.env 文件..."
ENV_FILE="$HERMES_HOME/.env"
cat > "$ENV_FILE" << 'ENV_EOF'
# Hermes Agent Environment Configuration
# Generated by hermes-setup.sh

# =============================================================================
# LLM PROVIDER — MiniMax CN（当前主力）
# =============================================================================
MINIMAX_CN_API_KEY=YOUR_MINIMAX_CN_API_KEY_HERE
MINIMAX_CN_GROUP_ID=YOUR_MINIMAX_CN_GROUP_ID_HERE

# =============================================================================
# GITHUB
# =============================================================================
GITHUB_TOKEN=YOUR_GITHUB_TOKEN_HERE

# =============================================================================
# FEISHU（飞书消息平台）
# =============================================================================
FEISHU_APP_ID=YOUR_FEISHU_APP_ID_HERE
FEISHU_APP_SECRET=YOUR_FEISHU_APP_SECRET_HERE
FEISHU_DOMAIN=feishu
FEISHU_ALLOW_ALL_USERS=true
FEISHU_ALLOWED_USERS=
FEISHU_GROUP_POLICY=open
FEISHU_CONNECTION_MODE=websocket
FEISHU_HOME_CHANNEL=YOUR_FEISHU_HOME_CHANNEL_ID_HERE

# =============================================================================
# TERMINAL TOOL
# =============================================================================
TERMINAL_ENV=local
TERMINAL_TIMEOUT=60
TERMINAL_LIFETIME_SECONDS=300

# =============================================================================
# BROWSER TOOL
# =============================================================================
BROWSERBASE_PROXIES=true
BROWSERBASE_ADVANCED_STEALTH=false
BROWSER_SESSION_TIMEOUT=300
BROWSER_INACTIVITY_TIMEOUT=120

# =============================================================================
# CONTEXT COMPRESSION
# =============================================================================
CONTEXT_COMPRESSION_ENABLED=true

# =============================================================================
# RL TRAINING (Tinker)
# =============================================================================
# TINKER_API_KEY=YOUR_TINKER_API_KEY_HERE
# WANDB_API_KEY=YOUR_WANDB_API_KEY_HERE
# RL_API_URL=http://localhost:8080

# =============================================================================
# DEBUG
# =============================================================================
WEB_TOOLS_DEBUG=false
VISION_TOOLS_DEBUG=false
MOA_TOOLS_DEBUG=false
IMAGE_TOOLS_DEBUG=false
ENV_EOF

# 替换占位符
sed -i "s|YOUR_MINIMAX_CN_API_KEY_HERE|${MINIMAX_CN_API_KEY}|g" "$ENV_FILE"
sed -i "s|YOUR_MINIMAX_CN_GROUP_ID_HERE|${MINIMAX_CN_GROUP_ID}|g" "$ENV_FILE"
sed -i "s|YOUR_GITHUB_TOKEN_HERE|${GITHUB_TOKEN}|g" "$ENV_FILE"
[[ -n "${FEISHU_APP_ID:-}" ]] && sed -i "s|YOUR_FEISHU_APP_ID_HERE|${FEISHU_APP_ID}|g" "$ENV_FILE"
[[ -n "${FEISHU_APP_SECRET:-}" ]] && sed -i "s|YOUR_FEISHU_APP_SECRET_HERE|${FEISHU_APP_SECRET}|g" "$ENV_FILE"
[[ -n "${FEISHU_HOME_CHANNEL:-}" ]] && sed -i "s|YOUR_FEISHU_HOME_CHANNEL_ID_HERE|${FEISHU_HOME_CHANNEL}|g" "$ENV_FILE"

ok ".env 文件生成完成"

# ─────────────────────────────────────────────
# 8. 生成 config.yaml
# ─────────────────────────────────────────────
info "生成 ~/.hermes/config.yaml..."
CONFIG_FILE="$HERMES_HOME/config.yaml"
cat > "$CONFIG_FILE" << 'YAML_EOF'
# Hermes Agent 配置文件
# Generated by hermes-setup.sh

model:
  default: MiniMax-M2.5-highspeed
  provider: minimax-cn

providers:
  minimax-cn:
    base_url: https://api.minimaxi.com/v1
    api_key: ${MINIMAX_CN_API_KEY}

terminal:
  backend: local
  cwd: .
  timeout: 180
  lifetime_seconds: 300
  container_cpu: 1
  container_memory: 5120
  container_disk: 51200
  container_persistent: true
  docker_mount_cwd_to_workspace: false

browser:
  inactivity_timeout: 120

compression:
  enabled: true
  threshold: 0.5
  target_ratio: 0.2
  protect_last_n: 20

# ECC Dev Autopilot — 开发类任务自动触发对应技能
ecc:
  dev_autopilot: true

memory:
  memory_enabled: true
  user_profile_enabled: true
  memory_char_limit: 2200
  user_char_limit: 1375
  nudge_interval: 10
  flush_min_turns: 6

session_reset:
  mode: both
  idle_minutes: 1440
  at_hour: 4

group_sessions_per_user: true

streaming:
  enabled: false

skills:
  creation_nudge_interval: 15

agent:
  max_turns: 60
  verbose: false
  reasoning_effort: medium

approvals:
  mode: off

stt:
  enabled: true
  local:
    model: base
  openai:
    model: whisper-1

code_execution:
  timeout: 300
  max_tool_calls: 50

delegation:
  max_iterations: 50
  default_toolsets:
    - terminal
    - file
    - web

display:
  compact: false
  tool_progress: all
  interim_assistant_messages: true
  busy_input_mode: interrupt
  background_process_notifications: all
  bell_on_complete: false
  show_reasoning: false
  streaming: true
  skin: default

minimax_group_id: ${MINIMAX_CN_GROUP_ID}
YAML_EOF

# 替换环境变量引用（实际运行时由 hermes 注入，这里用占位符）
sed -i "s|\${MINIMAX_CN_API_KEY}|${MINIMAX_CN_API_KEY}|g" "$CONFIG_FILE"
sed -i "s|\${MINIMAX_CN_GROUP_ID}|${MINIMAX_CN_GROUP_ID}|g" "$CONFIG_FILE"

ok "config.yaml 生成完成"

# ─────────────────────────────────────────────
# 9. 链接 hermes 命令
# ─────────────────────────────────────────────
info "链接 hermes 命令..."
BIN_DIR="$HERMES_HOME/bin"
mkdir -p "$BIN_DIR"
HERMES_BIN="$BIN_DIR/hermes"

# 方式1: python -m hermes_cli
cat > "$HERMES_BIN" << 'BIN_EOF'
#!/bin/bash
# Hermes Agent CLI 启动器
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
AGENT_DIR="$HERMES_HOME/hermes-agent"
source "$AGENT_DIR/venv/bin/activate"
export HERMES_HOME
exec python3 -m hermes_cli "$@"
BIN_EOF
chmod +x "$HERMES_BIN"

# 添加到 PATH（如果需要持久化）
SHELL_RC="${HOME}/.bashrc"
if [[ -f "$SHELL_RC" ]] && ! grep -q 'HERMES_HOME/bin' "$SHELL_RC"; then
    echo "export PATH=\"\$HOME/.hermes/bin:\$PATH\"" >> "$SHELL_RC"
    info "已添加 ~/.hermes/bin 到 PATH (~$SHELL_RC)"
fi

ok "hermes 命令链接完成"

# ─────────────────────────────────────────────
# 10. 记忆文件初始化（如果不存在）
# ─────────────────────────────────────────────
MEMORY_FILE="$HERMES_HOME/memories/MEMORY.md"
USER_FILE="$HERMES_HOME/memories/USER.md"

if [[ ! -f "$MEMORY_FILE" ]]; then
    info "初始化 MEMORY.md..."
    mkdir -p "$HERMES_HOME/memories"
    cat > "$MEMORY_FILE" << 'MEM_EOF'
# Hermes 记忆库 — 小赫的个人笔记

## 使用说明
本文件存储小赫在跨会话中积累的持久化知识。包括：
- 环境事实（工具行为、系统限制、工作目录约定）
- 项目约定（项目特有的代码规范、目录结构）
- 工具技巧（发现的新用法、常见错误）
- 学习总结（对某个问题/技术的深入理解）

## 不要存储
- 具体任务进度（用 session 记录）
- 敏感信息（密钥、密码、token）
- 动态数据（API 响应、文件内容）
- 主观评价或用户隐私信息

MEM_EOF
fi

if [[ ! -f "$USER_FILE" ]]; then
    info "初始化 USER.md..."
    cat > "$USER_FILE" << 'USER_EOF'
# 用户画像

## 基本信息
（由小赫在与用户交互中逐步填充）

## 偏好设置
- 语言：中文（简体中文）
- 输出风格：（待填充）
- 沟通方式：（待填充）

## 背景知识
- 感兴趣领域：（待填充）
- 厌恶事项：（待填充）
USER_EOF
fi

ok "记忆文件初始化完成"

# ─────────────────────────────────────────────
# 11. 安装默认 Skills（可选）
# ─────────────────────────────────────────────
info "检查 Skills 安装状态..."
SKILLS_DIR="$HERMES_HOME/skills"
mkdir -p "$SKILLS_DIR"

# 尝试从仓库复制 skills（如果存在）
HERMES_SKILLS="$AGENT_DIR/skills"
if [[ -d "$HERMES_SKILLS" && -n "$(ls -A "$HERMES_SKILLS" 2>/dev/null)" ]]; then
    # 复制用户的自定义 skills（排除 .git 和大型 submodule）
    info "从仓库复制 Skills..."
    for item in "$HERMES_SKILLS"/*/; do
        [[ -d "$item" ]] || continue
        name="$(basename "$item")"
        # 跳过大型/不需要的 skills
        case "$name" in
            everything-claude-code|awesome-design-md|markitdown) continue ;;
        esac
        if [[ ! -L "$SKILLS_DIR/$name" && ! -d "$SKILLS_DIR/$name" ]]; then
            cp -r "$item" "$SKILLS_DIR/$name"
            ok "已安装 skill: $name"
        fi
    done
fi

# ─────────────────────────────────────────────
# 12. 飞书连接（自动初始化）
# ─────────────────────────────────────────────
if [[ -n "${FEISHU_APP_ID:-}" && -n "${FEISHU_APP_SECRET:-}" ]]; then
    info "飞书配置已写入 .env"
    info "启用飞书连接：cd $AGENT_DIR && source venv/bin/activate && hermes gateway start"
    info "或使用: hermes feishu setup"
fi

# ─────────────────────────────────────────────
# 13. 清理 & 完成
# ─────────────────────────────────────────────
info "清理临时文件..."
# 清理 __pycache__
find "$AGENT_DIR" -type d -name '__pycache__' -exec rm -rf {} + 2>/dev/null || true

# ─────────────────────────────────────────────
# 14. 验证
# ─────────────────────────────────────────────
info "──────────────────────────────"
info "  验证安装"
info "──────────────────────────────"

ERRORS=0

# Python 版本
info "Python 版本: $(python3 --version)"
if python3 -c "import yaml, requests, rich" 2>/dev/null; then
    ok "核心依赖: yaml, requests, rich ✅"
else
    err "核心依赖缺失"
    ERRORS=$((ERRORS + 1))
fi

# hermes 模块
if python3 -c "import hermes_state" 2>/dev/null; then
    ok "hermes_state 模块 ✅"
else
    # 尝试从 agent dir 导入
    if PYTHONPATH="$AGENT_DIR:$PYTHONPATH" python3 -c "import hermes_state" 2>/dev/null; then
        ok "hermes_state 模块 (via PYTHONPATH) ✅"
    else
        warn "hermes_state 模块未找到（正常，代码未安装为包）"
    fi
fi

# 关键文件
for f in "$ENV_FILE" "$CONFIG_FILE" "$MEMORY_FILE" "$USER_FILE" "$HERMES_BIN"; do
    if [[ -f "$f" || -L "$f" ]]; then
        ok "文件存在: $(basename "$f")"
    else
        err "文件缺失: $f"
        ERRORS=$((ERRORS + 1))
    fi
done

# .env 安全性
if grep -q 'YOUR_.*_HERE' "$ENV_FILE" 2>/dev/null; then
    warn ".env 中仍有占位符未替换"
else
    ok ".env 已正确配置"
fi

# GitHub Token 检查
if grep -q "ghp_[a-zA-Z0-9]\{20,\}" "$ENV_FILE" 2>/dev/null; then
    ok "GitHub Token 已配置"
else
    warn "GitHub Token 未配置"
fi

# ─────────────────────────────────────────────
# 15. 使用说明
# ─────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ Hermes Agent 安装完成！${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo ""
echo "  配置目录: $HERMES_HOME"
echo "  代码目录: $AGENT_DIR"
echo "  Python:   $(python3 --version)"
echo ""
echo "  启动方式:"
echo "    cd $AGENT_DIR"
echo "    source venv/bin/activate"
echo "    hermes chat                    # 交互式对话"
echo "    hermes gateway start           # 启动飞书等消息网关"
echo "    hermes model                   # 查看/切换模型"
echo "    hermes skills                  # 管理 Skills"
echo ""
echo "  快捷命令:"
echo "    $HERMES_BIN chat               # 直接启动"
echo ""
echo "  配置文件:"
echo "    $ENV_FILE"
echo "    $CONFIG_FILE"
echo ""

if [[ $ERRORS -eq 0 ]]; then
    ok "安装验证通过 ✅"
else
    warn "发现 $ERRORS 个问题，请检查上述输出"
fi
